# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1368255bd2ce174fdf60e75b7f4e3eb7ac9a5a642af0de3ecf468db1b1603b32774592444565472b934a09b5003d9f498ad9e801303b18d5d54249313236bb2b

test:
  secret_key_base: cfe33f1403f00d94951f63722a5e4cee416b448c17f99567c47628a86dbfb981330f7be85e91d855737dc00d6972b1a9a6a408eae1d87f928cb3ac21e0d11b52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
